<?php

/**
 * Copyright (c) 2025 BroSolutions
 * All rights reserved
 *
 * This product includes proprietary software developed at BroSolutions, Ukraine
 * For more information see https://www.brosolutions.net/
 *
 * To obtain a valid license for using this software please contact us at
 * contact@brosolutions.net
 */

declare(strict_types=1);

use BroSolutions\QuickOrder\Block\Item\Renderer\SimpleRenderer;
use Magento\Framework\Escaper;

/**
 * @var SimpleRenderer $block
 * @var Escaper $escaper
 **/

$_item = $block->getItem(); ?>

<tr>
    <?php if ($_item->getIsNotAvailable()): ?>
        <td class="col name p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>">
            <span class="error-message"> <?= $escaper->escapeHtml(__($_item->getErrorMessage())) ?></span>
        </td>
    <?php else: ?>
        <td class="col name p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>">
            <span class="product name"><?= $escaper->escapeHtml($block->getName()) ?></span>
            <?php if ($_options = $block->getItemOptions()): ?>
                <dl class="item-options product-item-name">
                    <?php foreach ($_options as $_option): ?>
                        <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                        <dd><?= $escaper->escapeHtml($_option['print_value'] ?? $_option['value']) ?></dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col sku p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('SKU')) ?>">
        <span><?= $escaper->escapeHtml($block->prepareSku()) ?></span>
    </td>
    <?php if ($_item->getIsNotAvailable()): ?>
        <td class="col price p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        </td>
    <?php else: ?>
        <td class="col price p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <span> <?= $escaper->escapeHtml($block->getItemPriceHtml()) ?></span>
        </td>
    <?php endif; ?>
    <td class="col qty p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <span><?= $escaper->escapeHtml($block->getItemQuantity()) ?></span>
    </td>
    <td class="col subtotal p-2 text-start font-normal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <span><?= $escaper->escapeHtml($block->getItemRowTotalHtml()) ?></span>
    </td>
</tr>
